/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpeningRouteRouteImport } from './routes/opening/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaygroundIndexRouteImport } from './routes/playground/index'
import { Route as OpeningNameIndexRouteImport } from './routes/opening/$name/index'

const OpeningRouteRoute = OpeningRouteRouteImport.update({
  id: '/opening',
  path: '/opening',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundIndexRoute = PlaygroundIndexRouteImport.update({
  id: '/playground/',
  path: '/playground/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpeningNameIndexRoute = OpeningNameIndexRouteImport.update({
  id: '/$name/',
  path: '/$name/',
  getParentRoute: () => OpeningRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/opening': typeof OpeningRouteRouteWithChildren
  '/playground': typeof PlaygroundIndexRoute
  '/opening/$name': typeof OpeningNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/opening': typeof OpeningRouteRouteWithChildren
  '/playground': typeof PlaygroundIndexRoute
  '/opening/$name': typeof OpeningNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/opening': typeof OpeningRouteRouteWithChildren
  '/playground/': typeof PlaygroundIndexRoute
  '/opening/$name/': typeof OpeningNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/opening' | '/playground' | '/opening/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/opening' | '/playground' | '/opening/$name'
  id: '__root__' | '/' | '/opening' | '/playground/' | '/opening/$name/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpeningRouteRoute: typeof OpeningRouteRouteWithChildren
  PlaygroundIndexRoute: typeof PlaygroundIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/opening': {
      id: '/opening'
      path: '/opening'
      fullPath: '/opening'
      preLoaderRoute: typeof OpeningRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/': {
      id: '/playground/'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opening/$name/': {
      id: '/opening/$name/'
      path: '/$name'
      fullPath: '/opening/$name'
      preLoaderRoute: typeof OpeningNameIndexRouteImport
      parentRoute: typeof OpeningRouteRoute
    }
  }
}

interface OpeningRouteRouteChildren {
  OpeningNameIndexRoute: typeof OpeningNameIndexRoute
}

const OpeningRouteRouteChildren: OpeningRouteRouteChildren = {
  OpeningNameIndexRoute: OpeningNameIndexRoute,
}

const OpeningRouteRouteWithChildren = OpeningRouteRoute._addFileChildren(
  OpeningRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpeningRouteRoute: OpeningRouteRouteWithChildren,
  PlaygroundIndexRoute: PlaygroundIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
